...
...
    - .github/workflows/openshift.yml

GitHub Actions

/ .github/workflows/openshift.yml
...
...
….
...Google

ผู้ช่วยในบ้าน

Google Nest Hub

Google Nest Hub Max

Google Nest Mini

Google Home Mini

Google Home

Google Home Max

Google Nest Wifi Point (พร้อม Google Assistant)

Google Nest Audio

ความปลอดภัยและการรักษาความปลอดภัย

Google Nest Protect

ระบบสัญญาณกันขโมย Google Nest Secure (รวมถึง Google Nest Guard, Google Nest Detect, Google Nest Tag)

Google Nest Cam (แบบใช้สาย)

Google Nest Cam Indoor

Google Nest Cam ที่มีฟลัดไลท์

Google Nest Cam Outdoor

Google Nest Doorbell (แบบใช้แบตเตอรี่)

Google Nest Doorbell (แบบใช้สาย)

Google Nest Cam IQ Indoor

Google Nest Cam IQ Outdoor

Google Nest Cam (แบบใช้แบตเตอรี่)

Nest × Yale Lock

Google Nest Connect

บันเทิง

Chromecast

Chromecast Ultra

Chromecast Audio

Chromecast ที่มี Google TV

Chromecast Voice Remote

พลังงาน

Google Nest Learning Thermostat

Google Nest Thermostat E

Google Nest Temperature Sensor

Google Nest Heat Link

Google Nest Heat Link E

Google Nest Thermostat

การเชื่อมต่อ

เราเตอร์ Google Nest Wifi และ Point

Google Wifi

แอป

Google Home

Google Wifi

Nest

บริการ

Google Nest Aware

โปรแกรมประหยัดพลังงาน Rush Hour Rewards และ Seasonal Savings

ฟีเจอร์ใช้อินเทอร์เน็ตมือถือเป็นเครือข่ายสำรองพร้อมด้วย Google Nest Secure

Google Nest Renew

หมายเหตุ: ผลิตภัณฑ์กำลังอยู่ในช่วงเปลี่ยนแปลงแบรนด์ ซึ่งเป็นกระบวนการที่ใช้เวลา ดังนั้น แบรนด์ Google และ Nest อาจยังคงวางจำหน่ายแยกกันอยู่ในร้านค้าสำหรับช่วงเวลานี้
